### ISSUE TITLE
NullPointer at Load

### ISSUE THREAD

**Issue by drkthomp** [Dranion/JavaBot#1]
When attempting to load a saved file, Java runs into a NullPointerException. Interesting related things:
- The JavaDocs for DOTImporter don't show this as a likely exception to throw
- There are, to my knowledge, no null values being passed to DOTImporter

Here's the actual exception:

> Exception in thread "main" java.lang.NullPointerException
>   at org.jgrapht.ext.DOTImporter.processHeader(DOTImporter.java:281)
>   at org.jgrapht.ext.DOTImporter.read(DOTImporter.java:171)
>   at index.load(index.java:254)
>   at index.main(index.java:69)

The load method can be found at line 227 at index.java at this time.

**Comment by drkthomp** [comment]
ADDITION: 
It's triggering at graph.isAllowingMultipleEdges(), looking into that rn

FOLLOW-UP:
It's impossible for that method to return anything but false. Looking into it more

**Comment by drkthomp** [comment]
Graph is null at the location. What???

**Comment by drkthomp** [comment]
Hadn't declared the graph. Stupid! This is done now
